---
- name: Configure hosts & deploy application # <-- Словесное описание сценария (name)

hosts: all # <-- Для каких хостов будут выполняться описанные ниже таски (hosts)

tasks: # <-- Блок тасков (заданий), которые будут выполняться для данных хостов

